baseurl = "https://MirandaTilton.github.io/"
languageCode = "zh-cmn-Hant"
title = "Miranda Tilton"
theme = "hugo-bingo"


publishDir = "MirandaTilton.github.io"
disableHugoGeneratorInject = true
enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true
googleAnalytics = "UA-123-45"

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "CV"
    name = "Posts"
    url = "/cv"
    weight = 20
    
[params]

  [params.gravatar]
    email = "tiltonm@iastate.edu"

  [[params.social]]
    icon = "github"
    url = "https://github.com/MirandaTilton"
    weight = 10

  [[params.social]]
    icon = "twitter"
    url = "https://twitter.com/MirandaTilton"
    weight = 30

  [[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/miranda-tilton/"
    weight = 20
